import React, { createContext, useContext, useEffect, useState } from "react";

export type Language = "de" | "en" | "fr" | "ar";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
  dir: "ltr" | "rtl";
}

const translations: Record<Language, Record<string, string>> = {
  de: {
    // Nav
    nav_home: "Start",
    nav_concept: "Konzept",
    nav_brand: "Brand",
    nav_menu: "Speisekarte",
    nav_journey: "Journey",
    nav_workflow: "Workflow",
    nav_businessplan: "Businessplan",
    nav_contact: "Kontakt",

    // Hero
    hero_tagline: "Qualität trifft Mobilität",
    hero_subtitle: "Premium Smash Burger & Gourmet Baguettes – frisch zubereitet, direkt zu Ihnen.",
    hero_cta: "Speisekarte entdecken",
    hero_bp_cta: "Businessplan ansehen",

    // Concept
    concept_title: "Das Konzept",
    concept_subtitle: "Hochwertige Produkte. Fairer Preis. Flexibler Standort.",
    concept_text: "Burger & Baguette verbindet die Leidenschaft für handwerklich zubereitete Burger mit der Eleganz des französischen Baguettes. Unser Foodtruck bringt Premium-Street-Food direkt zu belebten Standorten – Einkaufszentren, Veranstaltungen und Firmenparkplätzen.",
    concept_quality: "Premium Qualität",
    concept_quality_desc: "Nur frische Zutaten, täglich geliefert",
    concept_mobile: "Maximale Flexibilität",
    concept_mobile_desc: "Überall dort, wo Kunden sind",
    concept_fair: "Fairer Preis",
    concept_fair_desc: "Gourmet-Erlebnis für jeden",

    // Menu
    menu_title: "Speisekarte",
    menu_burgers: "Smash Burger",
    menu_baguettes: "Gourmet Baguettes",
    menu_double: "Als Doppel-Patty",
    menu_double_desc: "+3,00 € Aufschlag",
    menu_deal: "Menü-Option",
    menu_deal_desc: "Jeder Burger oder jedes Baguette als Menü: +5,00 € = Pommes + Getränk + Sauce",
    menu_fresh: "Frisch zubereitet",
    menu_fresh_desc: "Alle Produkte werden frisch vor Ort zubereitet",

    // Burger names
    burger_classic: "Classic Smash",
    burger_classic_desc: "Rinderhack-Patty, Zwiebeln, Haussoße",
    burger_cheese: "Cheeseburger",
    burger_cheese_desc: "Rinderhack-Patty, Cheddar, Zwiebeln",
    burger_bacon: "Bacon Cheese",
    burger_bacon_desc: "Rinderhack-Patty, Cheddar, knuspriger Bacon, Zwiebeln",
    burger_onion: "Caramelized Onion",
    burger_onion_desc: "Rinderhack-Patty, Cheddar, karamellisierte Zwiebeln, Rucola",

    // Baguette names
    bag_hack: "Hack & Cheese",
    bag_hack_desc: "Würziges Rinderhack, geschmolzener Cheddar, Zwiebeln",
    bag_merguez: "Steak Baguette",
    bag_merguez_desc: "Saftiges Rindersteak, Röstzwiebeln, Pfeffersauce",
    bag_philly: "Philly Cheese Baguette",
    bag_philly_desc: "Zarter Rindersteak-Streifen, Paprika, Zwiebeln, geschmolzener Provolone",
    bag_veggi: "Veggie Mediterranean",
    bag_veggi_desc: "Gegrilltes Gemüse, Feta, Oliven, Rucola, Balsamico",

    // Extras & Drinks
    menu_extras: "Beilagen & Getränke",
    menu_fries: "Pommes Frites",
    menu_fries_desc: "Knusprig frittiert, nach Wahl gesalzen",
    menu_sauce: "Saucen",
    menu_sauce_desc: "Ketchup, Mayo, BBQ, Chili, Knoblauch",
    menu_drinks: "Softdrinks",
    menu_cola: "Cola",
    menu_fanta: "Fanta",
    menu_sprite: "Sprite",
    menu_icetea_lemon: "Eistee Lemon",
    menu_icetea_peach: "Eistee Pfirsich",
    menu_water: "Wasser Still",

    // Business Plan
    bp_title: "Businessplan",
    bp_tab_overview: "Übersicht",
    bp_tab_products: "Produkte",
    bp_tab_finance: "Finanzen",
    bp_tab_locations: "Standorte",
    bp_tab_roadmap: "Roadmap",

    // Overview tab
    bp_overview_title: "Konzept & Vision",
    bp_overview_text: "Burger & Baguette ist ein mobiles Foodtruck-Konzept, das hochwertige Smash Burger und Gourmet-Baguettes an frequentierten Standorten anbietet. Das Konzept verbindet Qualität mit Zugänglichkeit.",
    bp_invest_title: "Investition",
    bp_invest_total: "Gesamtinvestition",
    bp_invest_trailer: "Verkaufsanhänger VK 523",
    bp_invest_equip: "Küchenausstattung",
    bp_invest_brand: "Branding & Folierung",
    bp_invest_license: "Lizenzen & Genehmigungen",
    bp_invest_reserve: "Betriebskapital Reserve",

    // Finance tab
    bp_finance_title: "Wirtschaftlichkeit",
    bp_revenue_min: "Umsatz (Min.)",
    bp_revenue_max: "Umsatz (Max.)",
    bp_revenue_avg: "Umsatz (Ø)",
    bp_cogs: "Wareneinsatz",
    bp_rent: "Miete & Nebenkosten",
    bp_staff: "Personalkosten",
    bp_other: "Sonstige Kosten",
    bp_profit: "Gewinn vor Steuern",
    bp_monthly: "/ Monat",
    bp_breakeven: "Break-Even",
    bp_breakeven_val: "ca. 25.300 €",
    bp_roi: "Amortisation",
    bp_roi_val: "ca. 2–3 Monate",
    bp_margin: "Gewinnmarge",
    bp_margin_val: "38,5 %",

    // Locations tab
    bp_loc_title: "Standortstrategie",
    bp_loc_morning: "Vorbereitung",
    bp_loc_morning_desc: "Mise en place & Vorbereitung (09:00–11:00 Uhr) – kein Verkauf",
    bp_loc_midday: "Mittagsschicht",
    bp_loc_midday_desc: "Eröffnung & Mittagsgeschäft (11:00–15:00 Uhr)",
    bp_loc_evening: "Abendschicht",
    bp_loc_evening_desc: "Veranstaltungen, Märkte, Events (15:00–21:00 Uhr)",
    bp_loc_types: "Standorttypen",
    bp_loc_mall: "Einkaufszentren",
    bp_loc_event: "Veranstaltungen",
    bp_loc_corp: "Firmenparkplätze",
    bp_loc_market: "Wochenmärkte",

    // Roadmap tab
    bp_road_title: "Umsetzungsplan",
    bp_road_phase1: "Phase 1: Vorbereitung",
    bp_road_phase1_desc: "Anhänger bestellen, Genehmigungen beantragen, Branding finalisieren",
    bp_road_phase2: "Phase 2: Aufbau",
    bp_road_phase2_desc: "Küchenausstattung installieren, Lieferanten sichern, Personal einstellen",
    bp_road_phase3: "Phase 3: Soft Launch",
    bp_road_phase3_desc: "Erste Standorte testen, Feedback sammeln, Abläufe optimieren",
    bp_road_phase4: "Phase 4: Vollbetrieb",
    bp_road_phase4_desc: "3 Schichten täglich, feste Standortverträge, Expansion planen",
    bp_road_month: "Monat",

    // Home experience sections
    hero_eyebrow: "Mobile Gourmet · Foodtruck · Est. 2025",
    hero_stat_budget: "Startbudget",
    hero_stat_launch: "Monate bis Launch",
    hero_stat_goal: "Tagesziel",
    hero_scroll: "Scroll",

    concept_pillar_card_title: "Kompakte Karte",
    concept_pillar_card_text: "Wenige Signatures, kurze Wartezeit und eine klare Entscheidung am Counter.",
    concept_pillar_brand_title: "Marke im Alltag",
    concept_pillar_brand_text: "Truck, Uniform, Bag, Box und Wrap sprechen dieselbe visuelle Sprache.",
    concept_pillar_route_title: "Standortlogik",
    concept_pillar_route_text: "Lunch-Spots, Firmenparkplätze und Events als wiederholbare Route geplant.",
    concept_note_service_label: "Service",
    concept_note_service_text: "Bestellung bis Ausgabe unter Kontrolle",
    concept_note_quality_label: "Qualität",
    concept_note_quality_text: "Rezepturen und Verpackung standardisiert",
    concept_note_mobility_label: "Mobilität",
    concept_note_mobility_text: "Tageszeiten und Nachfrage flexibel bedienen",
    concept_note_brand_label: "Marke",
    concept_note_brand_text: "Konsistent erlebbar von Truck bis Tasche",
    concept_media_label: "Pilot Location",
    concept_media_number: "Konzept",
    concept_media_title: "Ein mobiles Konzept mit",
    concept_media_accent: "Restaurant-Niveau.",

    brand_eyebrow: "Brand System",
    brand_full_cta: "Brandseite ansehen",
    brand_head_pre: "Ein",
    brand_head_accent: "ruhiges System",
    brand_head_post: "für Truck, Team und Take-away.",
    brand_palette_label: "Farbpalette",
    brand_palette_note: "Vier Farben, viele Kontaktpunkte",
    brand_palette_ink_name: "Ink",
    brand_palette_ink_desc: "Tiefe & Kontrast",
    brand_palette_cream_name: "Cream",
    brand_palette_cream_desc: "Fläche & Ruhe",
    brand_palette_tan_name: "Tan",
    brand_palette_tan_desc: "Wärme & Textur",
    brand_palette_gold_name: "Gold",
    brand_palette_gold_desc: "Akzent & Signatur",
    brand_rollout_label: "Rollout Ready",
    brand_rollout_text: "Digital · Packaging · Uniform · Standort",
    brand_asset_truck_title: "Truck",
    brand_asset_truck_text: "Dunkle Flächen, warme Linien, weithin lesbares Logo.",
    brand_asset_packaging_title: "Packaging",
    brand_asset_packaging_text: "Bag, Box, Cup und Wrap tragen die Marke zum Gast.",
    brand_asset_team_title: "Team",
    brand_asset_team_text: "Uniformen machen Service und Marke zusammengehörig.",
    brand_asset_launch_title: "Launch",
    brand_asset_launch_text: "Standorte, Route und Auftritt wirken als ein System.",
    brand_mockups_eyebrow: "Mockups im Einsatz",
    brand_mockups_head_pre: "Reale Kontaktpunkte mit",
    brand_mockups_head_accent: "Inhalt",
    brand_mockups_head_post: ", nicht nur Logo-Flächen.",
    brand_mockups_copy: "Die Mockups zeigen, wie Packaging, Teamwear und Signage als System funktionieren: kurz lesbar, markentauglich und nah am Verkaufsmoment.",
    brand_mockup_box_title: "Burger Box",
    brand_mockup_box_label: "Take-away Signature",
    brand_mockup_box_text: "Logo, Pattern und Sticker machen die Verpackung auch nach dem Kauf sichtbar.",
    brand_mockup_wrap_title: "Baguette Wrap",
    brand_mockup_wrap_label: "Fresh Counter",
    brand_mockup_wrap_text: "Der Wrap bleibt ruhig und hochwertig, damit das Produkt im Vordergrund steht.",
    brand_mockup_counter_title: "Counter Bag",
    brand_mockup_counter_label: "Handoff Moment",
    brand_mockup_counter_text: "Die Tasche wird zur kleinen Werbefläche beim Übergang vom Truck zum Gast.",
    brand_mockup_paper_title: "Paper Bag",
    brand_mockup_paper_label: "Lunch Route",
    brand_mockup_paper_text: "Starke Lesbarkeit für Büro, Event, Markt und Laufkundschaft.",
    brand_mockup_teamwear_title: "Teamwear",
    brand_mockup_teamwear_label: "Service Look",
    brand_mockup_teamwear_text: "Dezentes Branding auf dunkler Kleidung hält das Team klar erkennbar.",
    brand_mockup_signboard_title: "Signboard",
    brand_mockup_signboard_label: "Street Signal",
    brand_mockup_signboard_text: "Das Schild macht Marke, Richtung und Angebot schon aus Distanz erfassbar.",

    menu_head_pre: "Wenig Auswahl,",
    menu_head_accent: "viel Klarheit.",
    menu_intro: "Smash Burger, warme Baguettes und Extras — so aufgebaut, dass Gäste schnell entscheiden und das Team sauber produzieren kann.",
    menu_tag_burger: "Smash Burger",
    menu_tag_baguettes: "Gourmet Baguettes",
    menu_tag_extras: "Fries & Drinks",
    menu_value_heat_title: "Signature Hitze",
    menu_value_heat_text: "Smash-Pattys werden kurz, heiß und wiederholbar produziert.",
    menu_value_upgrade_title: "Menü-Upgrade",
    menu_value_upgrade_text: "Drinks, Pommes und Saucen erhöhen den Bonwert ohne Komplexität.",
    menu_value_price_title: "Preise klar lesbar",
    menu_value_price_text: "Jede Kategorie bleibt kurz, verständlich und kalkulierbar.",

    standards_eyebrow: "Standards",
    standards_head_pre: "Ein Betriebssystem, das",
    standards_head_accent: "ruhig bleibt.",
    standards_copy: "Qualität entsteht nicht durch mehr Optionen, sondern durch klare Wiederholung. Jeder Standard ist ein Baustein des mobilen Betriebs.",
    standards_rule_label: "Core Rule",
    standards_rule_pre: "Weniger Varianten.",
    standards_rule_accent: "Mehr Kontrolle.",
    standard_ingredients_title: "Zutaten",
    standard_ingredients_text: "Spezifikationen für Buns, Fleisch, Gemüse und Saucen.",
    standard_recipe_title: "Rezeptur",
    standard_recipe_text: "Mengen, Garzeiten und Aufbau bleiben dokumentiert.",
    standard_speed_title: "Tempo",
    standard_speed_text: "Kurze Karte, klare Stationen, planbare Wartezeit.",
    standard_packaging_title: "Packaging",
    standard_packaging_text: "Transportstabil und sichtbar gebrandet.",
    standard_control_title: "Kontrolle",
    standard_control_text: "Temperaturen, Reinigung und Mise en place als Checkliste.",
    standard_location_title: "Standort",
    standard_location_text: "Strom, Wasser, Ausgabe und Queue werden vorab geprüft.",

    journey_eyebrow: "Customer Journey",
    journey_head_pre: "Vom ersten Blick bis",
    journey_head_accent: "zur Tasche.",
    journey_copy: "Das Erlebnis ist kurz, aber es muss sitzen: sehen, verstehen, bestellen, erhalten. Jeder Moment hat eine klare Aufgabe.",
    journey_step_visible_title: "Sichtbar werden",
    journey_step_visible_text: "Truck, Licht und Marke setzen den ersten Impuls schon aus der Distanz.",
    journey_step_order_title: "Schnell bestellen",
    journey_step_order_text: "Die Karte bleibt kurz, damit die Entscheidung am Counter ohne Reibung passiert.",
    journey_step_wait_title: "Ruhig warten",
    journey_step_wait_text: "Fixe Stationen und vorbereitete Zutaten halten den Ablauf stabil.",
    journey_step_takeaway_title: "Marke mitnehmen",
    journey_step_takeaway_text: "Bag, Cup und Wrap tragen den Eindruck bis ins Büro, Event oder nach Hause.",

    workflow_eyebrow: "Workflow",
    workflow_head_pre: "Ein kleiner Truck, ein",
    workflow_head_accent: "präziser Ablauf.",
    workflow_copy: "Die operative Gestaltung ist so wichtig wie das Branding. Alles ist auf kurze Wege und klare Rollen ausgelegt.",
    workflow_media_label: "Kitchen Workflow",
    workflow_day_label: "Daily System",
    workflow_phase_prep_title: "Prep vor Öffnung",
    workflow_phase_prep_text: "Mise en place, Stationen, Lager",
    workflow_phase_lunch_title: "Lunch-Service",
    workflow_phase_lunch_text: "Höchste Frequenz, kurze Wege",
    workflow_phase_event_title: "Event / Abend",
    workflow_phase_event_text: "Flexible Route nach Nachfrage",
    workflow_phase_clean_title: "Clean-down",
    workflow_phase_clean_text: "Reinigung, Abschluss, Übergabe",
    workflow_lane_buy_title: "Einkauf",
    workflow_lane_buy_text: "Kurze Lieferliste, bessere Planung, weniger Abfall.",
    workflow_lane_mise_title: "Mise en place",
    workflow_lane_mise_text: "Vorbereitung macht Stoßzeiten ruhiger.",
    workflow_lane_production_title: "Produktion",
    workflow_lane_production_text: "Griddle, Baguette-Station, Ausgabe als Linie.",
    workflow_lane_pace_title: "Tempo",
    workflow_lane_pace_text: "Bonwert, Wartezeit und Durchsatz sichtbar.",
    workflow_lane_roles_title: "Teamrollen",
    workflow_lane_roles_text: "Kasse, Griddle, Assembly klar getrennt.",

    business_eyebrow: "Businessplan",
    business_head_pre: "Zahlen, Route und Marke in",
    business_head_accent: "einem Modell.",
    business_copy: "Der Plan ist als Startsystem gedacht: investierbar, messbar und schlank genug, um nach dem Pilotbetrieb angepasst zu werden.",
    business_kpi_invest_label: "Startinvestition",
    business_kpi_invest_text: "Trailer, Ausstattung, Branding, Genehmigung & Reserve.",
    business_kpi_margin_label: "Zielmarge",
    business_kpi_margin_text: "Auf kurzer Karte und wiederholbarer Produktion kalkuliert.",
    business_kpi_pilot_label: "Monate bis Pilot",
    business_kpi_pilot_text: "Von Setup bis Soft Launch im Pilotbetrieb.",
    business_invest_title: "Investitionsmix",
    business_invest_trailer: "Trailer",
    business_invest_equipment: "Equipment",
    business_invest_brand: "Branding",
    business_invest_license: "Lizenz & Reserve",
    business_finance_title: "Monatslogik",
    business_finance_revenue: "Umsatz Ø",
    business_finance_cogs: "Wareneinsatz",
    business_finance_staff: "Personal",
    business_finance_reserve: "Reserve",
    business_product_burger_label: "Smash Burger",
    business_product_burger_value: "4 Signatures",
    business_product_baguette_label: "Gourmet Baguettes",
    business_product_baguette_value: "4 Varianten",
    business_product_extras_label: "Extras",
    business_product_extras_value: "Pommes, Saucen, Drinks",
    business_roadmap_label: "Roadmap",
    business_road_setup_title: "Setup",
    business_road_setup_text: "Truck, Equipment, Branding",
    business_road_test_title: "Test",
    business_road_test_text: "Rezepte, Einkauf, Servicezeiten",
    business_road_pilot_title: "Pilot",
    business_road_pilot_text: "Lunch-Spots und Event-Slots",
    business_road_scale_title: "Scale",
    business_road_scale_text: "Playbook für weitere Standorte",
    business_closing_head_pre: "Die Marke verkauft mit, aber der",
    business_closing_head_accent: "Ablauf entscheidet.",
    business_closing_copy: "Deshalb verbindet der Plan Brand-Assets, Standortwahl, Menu-Engineering und Messpunkte in einem überschaubaren Startmodell.",
    business_launch_cta: "Launch ansehen",

    launch_eyebrow: "Launch Plan",
    launch_head_pre: "Vom ersten Slot zum",
    launch_head_accent: "wiederholbaren Betrieb.",
    launch_copy: "Burger & Baguette startet nicht als große Show, sondern als messbarer Pilot: gute Standorte, saubere Abläufe, klare Marke.",
    launch_business_cta: "Businessplan ansehen",
    launch_menu_cta: "Speisekarte",
    launch_check_locations_title: "Pilotstandorte",
    launch_check_locations_text: "Zuerst wenige Standorte mit klarer Frequenz testen.",
    launch_check_route_title: "Route",
    launch_check_route_text: "Lunch, Feierabend und Events als wiederkehrende Woche planen.",
    launch_check_metrics_title: "Kennzahlen",
    launch_check_metrics_text: "Bonwert, Wartezeit, Tagesumsatz und Retourenquote täglich sehen.",
    launch_check_scale_title: "Skalierung",
    launch_check_scale_text: "Nach dem Pilot Rezepturen und Teamrollen als Playbook fixieren.",

    footer_tagline: "Qualität trifft Mobilität",
    footer_copy: "Handwerkliche Burger, frische Baguettes und ein klarer Auftritt für mobile Gastronomie mit Premium-Anspruch.",
    footer_highlight_mobile: "Mobile Gourmet",
    footer_highlight_truck: "Foodtruck",
    footer_highlight_event: "Event & Lunch",
    footer_nav_title: "Explore",
    footer_meta: "Mobile Gourmet · Foodtruck",

    // Footer
    footer_rights: "Alle Rechte vorbehalten",
    footer_concept: "Ein Konzept von Burger & Baguette",
  },
  en: {
    nav_home: "Home",
    nav_concept: "Concept",
    nav_brand: "Brand",
    nav_menu: "Menu",
    nav_journey: "Journey",
    nav_workflow: "Workflow",
    nav_businessplan: "Business Plan",
    nav_contact: "Contact",

    hero_tagline: "Quality Meets Mobility",
    hero_subtitle: "Premium Smash Burgers & Gourmet Baguettes – freshly prepared, right where you are.",
    hero_cta: "Explore the Menu",
    hero_bp_cta: "View Business Plan",

    concept_title: "The Concept",
    concept_subtitle: "Premium Products. Fair Prices. Flexible Locations.",
    concept_text: "Burger & Baguette combines the passion for handcrafted burgers with the elegance of the French baguette. Our food truck brings premium street food directly to busy locations – shopping centers, events, and corporate parking lots.",
    concept_quality: "Premium Quality",
    concept_quality_desc: "Only fresh ingredients, delivered daily",
    concept_mobile: "Maximum Flexibility",
    concept_mobile_desc: "Wherever customers are",
    concept_fair: "Fair Prices",
    concept_fair_desc: "Gourmet experience for everyone",

    menu_title: "Menu",
    menu_burgers: "Smash Burgers",
    menu_baguettes: "Gourmet Baguettes",
    menu_double: "As Double Patty",
    menu_double_desc: "+€3.00 surcharge",
    menu_deal: "Meal Deal",
    menu_deal_desc: "Any burger or baguette as a meal: +€5.00 = Fries + Drink + Sauce",
    menu_fresh: "Freshly Prepared",
    menu_fresh_desc: "All products are freshly prepared on site",

    burger_classic: "Classic Smash",
    burger_classic_desc: "Beef patty, onions, house sauce",
    burger_cheese: "Cheeseburger",
    burger_cheese_desc: "Beef patty, cheddar, onions",
    burger_bacon: "Bacon Cheese",
    burger_bacon_desc: "Beef patty, cheddar, crispy bacon, onions",
    burger_onion: "Caramelized Onion",
    burger_onion_desc: "Beef patty, cheddar, caramelized onions, arugula",

    bag_hack: "Beef & Cheese",
    bag_hack_desc: "Spiced ground beef, melted cheddar, onions",
    bag_merguez: "Steak Baguette",
    bag_merguez_desc: "Juicy beef steak, crispy onions, pepper sauce",
    bag_philly: "Philly Cheese Baguette",
    bag_philly_desc: "Tender beef strips, peppers, onions, melted provolone",
    bag_veggi: "Veggie Mediterranean",
    bag_veggi_desc: "Grilled vegetables, feta, olives, arugula, balsamic",

    menu_extras: "Sides & Drinks",
    menu_fries: "French Fries",
    menu_fries_desc: "Crispy fried, salted to taste",
    menu_sauce: "Sauces",
    menu_sauce_desc: "Ketchup, Mayo, BBQ, Chili, Garlic",
    menu_drinks: "Soft Drinks",
    menu_cola: "Cola",
    menu_fanta: "Fanta",
    menu_sprite: "Sprite",
    menu_icetea_lemon: "Iced Tea Lemon",
    menu_icetea_peach: "Iced Tea Peach",
    menu_water: "Still Water",

    bp_title: "Business Plan",
    bp_tab_overview: "Overview",
    bp_tab_products: "Products",
    bp_tab_finance: "Financials",
    bp_tab_locations: "Locations",
    bp_tab_roadmap: "Roadmap",

    bp_overview_title: "Concept & Vision",
    bp_overview_text: "Burger & Baguette is a mobile food truck concept offering premium smash burgers and gourmet baguettes at high-traffic locations. The concept combines quality with accessibility.",
    bp_invest_title: "Investment",
    bp_invest_total: "Total Investment",
    bp_invest_trailer: "Sales Trailer VK 523",
    bp_invest_equip: "Kitchen Equipment",
    bp_invest_brand: "Branding & Wrapping",
    bp_invest_license: "Licenses & Permits",
    bp_invest_reserve: "Working Capital Reserve",

    bp_finance_title: "Profitability",
    bp_revenue_min: "Revenue (Min.)",
    bp_revenue_max: "Revenue (Max.)",
    bp_revenue_avg: "Revenue (Avg.)",
    bp_cogs: "Cost of Goods",
    bp_rent: "Rent & Utilities",
    bp_staff: "Staff Costs",
    bp_other: "Other Costs",
    bp_profit: "Profit Before Tax",
    bp_monthly: "/ month",
    bp_breakeven: "Break-Even",
    bp_breakeven_val: "approx. €25,300",
    bp_roi: "Payback Period",
    bp_roi_val: "approx. 2–3 months",
    bp_margin: "Profit Margin",
    bp_margin_val: "38.5%",

    bp_loc_title: "Location Strategy",
    bp_loc_morning: "Preparation",
    bp_loc_morning_desc: "Mise en place & prep (9:00–11:00 am) – no sales",
    bp_loc_midday: "Lunch Shift",
    bp_loc_midday_desc: "Opening & lunch service (11:00 am–3:00 pm)",
    bp_loc_evening: "Evening Shift",
    bp_loc_evening_desc: "Events, markets, festivals (3:00–9:00 pm)",
    bp_loc_types: "Location Types",
    bp_loc_mall: "Shopping Centers",
    bp_loc_event: "Events",
    bp_loc_corp: "Corporate Parks",
    bp_loc_market: "Weekly Markets",

    bp_road_title: "Implementation Plan",
    bp_road_phase1: "Phase 1: Preparation",
    bp_road_phase1_desc: "Order trailer, apply for permits, finalize branding",
    bp_road_phase2: "Phase 2: Setup",
    bp_road_phase2_desc: "Install kitchen, secure suppliers, hire staff",
    bp_road_phase3: "Phase 3: Soft Launch",
    bp_road_phase3_desc: "Test first locations, collect feedback, optimize operations",
    bp_road_phase4: "Phase 4: Full Operations",
    bp_road_phase4_desc: "3 shifts daily, fixed location contracts, plan expansion",
    bp_road_month: "Month",

    // Home experience sections
    hero_eyebrow: "Mobile Gourmet · Food Truck · Est. 2025",
    hero_stat_budget: "Starting budget",
    hero_stat_launch: "Months to launch",
    hero_stat_goal: "Daily target",
    hero_scroll: "Scroll",

    concept_pillar_card_title: "Compact Menu",
    concept_pillar_card_text: "A few signatures, short wait times, and a clear counter decision.",
    concept_pillar_brand_title: "Brand in Use",
    concept_pillar_brand_text: "Truck, uniform, bag, box, and wrap speak the same visual language.",
    concept_pillar_route_title: "Location Logic",
    concept_pillar_route_text: "Lunch spots, company parking lots, and events planned as a repeatable route.",
    concept_note_service_label: "Service",
    concept_note_service_text: "Order-to-handoff stays controlled",
    concept_note_quality_label: "Quality",
    concept_note_quality_text: "Recipes and packaging are standardized",
    concept_note_mobility_label: "Mobility",
    concept_note_mobility_text: "Serve different dayparts and demand flexibly",
    concept_note_brand_label: "Brand",
    concept_note_brand_text: "Consistent from truck to takeaway bag",
    concept_media_label: "Pilot Location",
    concept_media_number: "Concept",
    concept_media_title: "A mobile concept with",
    concept_media_accent: "restaurant-level quality.",

    brand_eyebrow: "Brand System",
    brand_full_cta: "See Full Brand",
    brand_head_pre: "A",
    brand_head_accent: "quiet system",
    brand_head_post: "for truck, team, and takeaway.",
    brand_palette_label: "Color Palette",
    brand_palette_note: "Four colors, many touchpoints",
    brand_palette_ink_name: "Ink",
    brand_palette_ink_desc: "Depth & contrast",
    brand_palette_cream_name: "Cream",
    brand_palette_cream_desc: "Space & calm",
    brand_palette_tan_name: "Tan",
    brand_palette_tan_desc: "Warmth & texture",
    brand_palette_gold_name: "Gold",
    brand_palette_gold_desc: "Accent & signature",
    brand_rollout_label: "Rollout Ready",
    brand_rollout_text: "Digital · Packaging · Uniform · Location",
    brand_asset_truck_title: "Truck",
    brand_asset_truck_text: "Dark surfaces, warm lines, and a logo readable from distance.",
    brand_asset_packaging_title: "Packaging",
    brand_asset_packaging_text: "Bag, box, cup, and wrap carry the brand to the guest.",
    brand_asset_team_title: "Team",
    brand_asset_team_text: "Uniforms make service and brand feel connected.",
    brand_asset_launch_title: "Launch",
    brand_asset_launch_text: "Locations, route, and presence work as one system.",
    brand_mockups_eyebrow: "Mockups in Use",
    brand_mockups_head_pre: "Real touchpoints with",
    brand_mockups_head_accent: "content",
    brand_mockups_head_post: ", not just logo space.",
    brand_mockups_copy: "The mockups show how packaging, teamwear, and signage work as a system: easy to read, brand-ready, and close to the sales moment.",
    brand_mockup_box_title: "Burger Box",
    brand_mockup_box_label: "Take-away Signature",
    brand_mockup_box_text: "Logo, pattern, and sticker keep the packaging visible after purchase.",
    brand_mockup_wrap_title: "Baguette Wrap",
    brand_mockup_wrap_label: "Fresh Counter",
    brand_mockup_wrap_text: "The wrap stays calm and premium so the product remains the focus.",
    brand_mockup_counter_title: "Counter Bag",
    brand_mockup_counter_label: "Handoff Moment",
    brand_mockup_counter_text: "The bag becomes a small advertising surface between truck and guest.",
    brand_mockup_paper_title: "Paper Bag",
    brand_mockup_paper_label: "Lunch Route",
    brand_mockup_paper_text: "Strong readability for office, event, market, and walk-up guests.",
    brand_mockup_teamwear_title: "Teamwear",
    brand_mockup_teamwear_label: "Service Look",
    brand_mockup_teamwear_text: "Subtle branding on dark clothing keeps the team clearly recognizable.",
    brand_mockup_signboard_title: "Signboard",
    brand_mockup_signboard_label: "Street Signal",
    brand_mockup_signboard_text: "The sign makes brand, direction, and offer clear from a distance.",

    menu_head_pre: "Few choices,",
    menu_head_accent: "clear decisions.",
    menu_intro: "Smash burgers, warm baguettes, and extras are structured so guests decide quickly and the team can produce cleanly.",
    menu_tag_burger: "Smash Burger",
    menu_tag_baguettes: "Gourmet Baguettes",
    menu_tag_extras: "Fries & Drinks",
    menu_value_heat_title: "Signature Heat",
    menu_value_heat_text: "Smash patties are produced fast, hot, and repeatably.",
    menu_value_upgrade_title: "Meal Upgrade",
    menu_value_upgrade_text: "Drinks, fries, and sauces lift the ticket value without complexity.",
    menu_value_price_title: "Clear Pricing",
    menu_value_price_text: "Every category stays short, readable, and easy to calculate.",

    standards_eyebrow: "Standards",
    standards_head_pre: "An operating system that",
    standards_head_accent: "stays calm.",
    standards_copy: "Quality does not come from more options, but from clear repetition. Every standard is a building block of mobile operations.",
    standards_rule_label: "Core Rule",
    standards_rule_pre: "Fewer variants.",
    standards_rule_accent: "More control.",
    standard_ingredients_title: "Ingredients",
    standard_ingredients_text: "Specifications for buns, beef, vegetables, and sauces.",
    standard_recipe_title: "Recipe",
    standard_recipe_text: "Quantities, cook times, and build order stay documented.",
    standard_speed_title: "Pace",
    standard_speed_text: "Short menu, clear stations, predictable wait time.",
    standard_packaging_title: "Packaging",
    standard_packaging_text: "Transport-stable and visibly branded.",
    standard_control_title: "Control",
    standard_control_text: "Temperatures, cleaning, and mise en place as a checklist.",
    standard_location_title: "Location",
    standard_location_text: "Power, water, handoff, and queue are checked in advance.",

    journey_eyebrow: "Customer Journey",
    journey_head_pre: "From first glance to",
    journey_head_accent: "the bag.",
    journey_copy: "The experience is short, but it has to land: see, understand, order, receive. Every moment has a clear job.",
    journey_step_visible_title: "Become Visible",
    journey_step_visible_text: "Truck, light, and brand create the first impulse from a distance.",
    journey_step_order_title: "Order Fast",
    journey_step_order_text: "The menu stays short so the counter decision happens without friction.",
    journey_step_wait_title: "Wait Calmly",
    journey_step_wait_text: "Fixed stations and prepared ingredients keep the flow stable.",
    journey_step_takeaway_title: "Carry the Brand",
    journey_step_takeaway_text: "Bag, cup, and wrap carry the impression to the office, event, or home.",

    workflow_eyebrow: "Workflow",
    workflow_head_pre: "A small truck, a",
    workflow_head_accent: "precise flow.",
    workflow_copy: "Operational design matters as much as branding. Everything is built for short paths and clear roles.",
    workflow_media_label: "Kitchen Workflow",
    workflow_day_label: "Daily System",
    workflow_phase_prep_title: "Pre-opening Prep",
    workflow_phase_prep_text: "Mise en place, stations, storage",
    workflow_phase_lunch_title: "Lunch Service",
    workflow_phase_lunch_text: "Highest frequency, shortest paths",
    workflow_phase_event_title: "Event / Evening",
    workflow_phase_event_text: "Flexible route based on demand",
    workflow_phase_clean_title: "Clean-down",
    workflow_phase_clean_text: "Cleaning, closing, handover",
    workflow_lane_buy_title: "Purchasing",
    workflow_lane_buy_text: "Short supplier list, better planning, less waste.",
    workflow_lane_mise_title: "Mise en place",
    workflow_lane_mise_text: "Preparation makes peak hours calmer.",
    workflow_lane_production_title: "Production",
    workflow_lane_production_text: "Griddle, baguette station, and handoff as one line.",
    workflow_lane_pace_title: "Pace",
    workflow_lane_pace_text: "Ticket value, wait time, and throughput stay visible.",
    workflow_lane_roles_title: "Team Roles",
    workflow_lane_roles_text: "Cashier, griddle, and assembly are clearly separated.",

    business_eyebrow: "Business Plan",
    business_head_pre: "Numbers, route, and brand in",
    business_head_accent: "one model.",
    business_copy: "The plan is built as a starting system: investable, measurable, and lean enough to adjust after the pilot.",
    business_kpi_invest_label: "Starting Investment",
    business_kpi_invest_text: "Trailer, equipment, branding, permit, and reserve.",
    business_kpi_margin_label: "Target Margin",
    business_kpi_margin_text: "Calculated around a short menu and repeatable production.",
    business_kpi_pilot_label: "Months to Pilot",
    business_kpi_pilot_text: "From setup to soft launch in pilot operations.",
    business_invest_title: "Investment Mix",
    business_invest_trailer: "Trailer",
    business_invest_equipment: "Equipment",
    business_invest_brand: "Branding",
    business_invest_license: "License & Reserve",
    business_finance_title: "Monthly Logic",
    business_finance_revenue: "Revenue Avg.",
    business_finance_cogs: "Cost of Goods",
    business_finance_staff: "Staff",
    business_finance_reserve: "Reserve",
    business_product_burger_label: "Smash Burger",
    business_product_burger_value: "4 signatures",
    business_product_baguette_label: "Gourmet Baguettes",
    business_product_baguette_value: "4 variants",
    business_product_extras_label: "Extras",
    business_product_extras_value: "Fries, sauces, drinks",
    business_roadmap_label: "Roadmap",
    business_road_setup_title: "Setup",
    business_road_setup_text: "Truck, equipment, branding",
    business_road_test_title: "Test",
    business_road_test_text: "Recipes, purchasing, service hours",
    business_road_pilot_title: "Pilot",
    business_road_pilot_text: "Lunch spots and event slots",
    business_road_scale_title: "Scale",
    business_road_scale_text: "Playbook for more locations",
    business_closing_head_pre: "The brand helps sell, but the",
    business_closing_head_accent: "flow decides.",
    business_closing_copy: "That is why the plan connects brand assets, location choice, menu engineering, and measurement points in a manageable starting model.",
    business_launch_cta: "View launch",

    launch_eyebrow: "Launch Plan",
    launch_head_pre: "From first slot to",
    launch_head_accent: "repeatable operations.",
    launch_copy: "Burger & Baguette does not start as a big show, but as a measurable pilot: good locations, clean operations, clear brand.",
    launch_business_cta: "View business plan",
    launch_menu_cta: "Menu",
    launch_check_locations_title: "Pilot Locations",
    launch_check_locations_text: "Test a few locations with clear footfall first.",
    launch_check_route_title: "Route",
    launch_check_route_text: "Plan lunch, after-work, and events as a recurring week.",
    launch_check_metrics_title: "Metrics",
    launch_check_metrics_text: "Track ticket value, wait time, daily revenue, and return rate.",
    launch_check_scale_title: "Scaling",
    launch_check_scale_text: "After the pilot, lock recipes and team roles into a playbook.",

    footer_tagline: "Quality Meets Mobility",
    footer_copy: "Handcrafted burgers, fresh baguettes, and a clear presence for premium mobile gastronomy.",
    footer_highlight_mobile: "Mobile Gourmet",
    footer_highlight_truck: "Food Truck",
    footer_highlight_event: "Event & Lunch",
    footer_nav_title: "Explore",
    footer_meta: "Mobile Gourmet · Food Truck",

    footer_rights: "All rights reserved",
    footer_concept: "A concept by Burger & Baguette",
  },
  fr: {
    nav_home: "Accueil",
    nav_concept: "Concept",
    nav_brand: "Marque",
    nav_menu: "Menu",
    nav_journey: "Parcours",
    nav_workflow: "Workflow",
    nav_businessplan: "Business Plan",
    nav_contact: "Contact",

    hero_tagline: "La Qualité en Mouvement",
    hero_subtitle: "Smash Burgers Premium & Baguettes Gourmet – préparés frais, là où vous êtes.",
    hero_cta: "Découvrir le Menu",
    hero_bp_cta: "Voir le Business Plan",

    concept_title: "Le Concept",
    concept_subtitle: "Produits Premium. Prix Justes. Emplacements Flexibles.",
    concept_text: "Burger & Baguette allie la passion des burgers artisanaux à l'élégance de la baguette française. Notre food truck apporte le street food premium directement dans les lieux animés – centres commerciaux, événements et parkings d'entreprises.",
    concept_quality: "Qualité Premium",
    concept_quality_desc: "Uniquement des ingrédients frais, livrés quotidiennement",
    concept_mobile: "Flexibilité Maximale",
    concept_mobile_desc: "Là où se trouvent les clients",
    concept_fair: "Prix Justes",
    concept_fair_desc: "L'expérience gastronomique pour tous",

    menu_title: "Menu",
    menu_burgers: "Smash Burgers",
    menu_baguettes: "Baguettes Gourmet",
    menu_double: "En Double Patty",
    menu_double_desc: "+3,00 € de supplément",
    menu_deal: "Menu Complet",
    menu_deal_desc: "Tout burger ou baguette en menu: +5,00 € = Frites + Boisson + Sauce",
    menu_fresh: "Préparé Frais",
    menu_fresh_desc: "Tous les produits sont préparés frais sur place",

    burger_classic: "Classic Smash",
    burger_classic_desc: "Steak haché, oignons, sauce maison",
    burger_cheese: "Cheeseburger",
    burger_cheese_desc: "Steak haché, cheddar, oignons",
    burger_bacon: "Bacon Cheese",
    burger_bacon_desc: "Steak haché, cheddar, bacon croustillant, oignons",
    burger_onion: "Oignons Caramélisés",
    burger_onion_desc: "Steak haché, cheddar, oignons caramélisés, roquette",

    bag_hack: "Bœuf & Fromage",
    bag_hack_desc: "Bœuf haché épicé, cheddar fondu, oignons",
    bag_merguez: "Baguette Steak",
    bag_merguez_desc: "Steak de bœuf juteux, oignons croustillants, sauce poivre",
    bag_philly: "Baguette Philly Cheese",
    bag_philly_desc: "Lamelles de bœuf tendres, poivrons, oignons, provolone fondu",
    bag_veggi: "Veggie Méditerranée",
    bag_veggi_desc: "Légumes grillés, feta, olives, roquette, balsamique",

    menu_extras: "Accompagnements & Boissons",
    menu_fries: "Frites",
    menu_fries_desc: "Frites croustillantes, salées selon goût",
    menu_sauce: "Sauces",
    menu_sauce_desc: "Ketchup, Mayo, BBQ, Chili, Ail",
    menu_drinks: "Boissons Fraîches",
    menu_cola: "Cola",
    menu_fanta: "Fanta",
    menu_sprite: "Sprite",
    menu_icetea_lemon: "Thé Glacé Citron",
    menu_icetea_peach: "Thé Glacé Pêche",
    menu_water: "Eau Plate",

    bp_title: "Business Plan",
    bp_tab_overview: "Aperçu",
    bp_tab_products: "Produits",
    bp_tab_finance: "Finances",
    bp_tab_locations: "Emplacements",
    bp_tab_roadmap: "Feuille de Route",

    bp_overview_title: "Concept & Vision",
    bp_overview_text: "Burger & Baguette est un concept de food truck mobile proposant des smash burgers premium et des baguettes gourmet dans des lieux à fort trafic. Le concept allie qualité et accessibilité.",
    bp_invest_title: "Investissement",
    bp_invest_total: "Investissement Total",
    bp_invest_trailer: "Remorque de Vente VK 523",
    bp_invest_equip: "Équipement de Cuisine",
    bp_invest_brand: "Branding & Covering",
    bp_invest_license: "Licences & Autorisations",
    bp_invest_reserve: "Réserve de Fonds de Roulement",

    bp_finance_title: "Rentabilité",
    bp_revenue_min: "Chiffre d'Affaires (Min.)",
    bp_revenue_max: "Chiffre d'Affaires (Max.)",
    bp_revenue_avg: "Chiffre d'Affaires (Moy.)",
    bp_cogs: "Coût des Marchandises",
    bp_rent: "Loyer & Charges",
    bp_staff: "Charges de Personnel",
    bp_other: "Autres Charges",
    bp_profit: "Bénéfice Avant Impôts",
    bp_monthly: "/ mois",
    bp_breakeven: "Seuil de Rentabilité",
    bp_breakeven_val: "env. 25 300 €",
    bp_roi: "Retour sur Investissement",
    bp_roi_val: "env. 2–3 mois",
    bp_margin: "Marge Bénéficiaire",
    bp_margin_val: "38,5 %",

    bp_loc_title: "Stratégie d'Emplacement",
    bp_loc_morning: "Préparation",
    bp_loc_morning_desc: "Mise en place & préparation (9h–11h) – pas de vente",
    bp_loc_midday: "Service du midi",
    bp_loc_midday_desc: "Ouverture & service du déjeuner (11h–15h)",
    bp_loc_evening: "Service du soir",
    bp_loc_evening_desc: "Événements, marchés, festivals (15h–21h)",
    bp_loc_types: "Types d'Emplacements",
    bp_loc_mall: "Centres Commerciaux",
    bp_loc_event: "Événements",
    bp_loc_corp: "Parcs d'Entreprises",
    bp_loc_market: "Marchés Hebdomadaires",

    bp_road_title: "Plan de Mise en Œuvre",
    bp_road_phase1: "Phase 1 : Préparation",
    bp_road_phase1_desc: "Commander la remorque, demander les autorisations, finaliser le branding",
    bp_road_phase2: "Phase 2 : Installation",
    bp_road_phase2_desc: "Installer la cuisine, sécuriser les fournisseurs, recruter le personnel",
    bp_road_phase3: "Phase 3 : Lancement Doux",
    bp_road_phase3_desc: "Tester les premiers emplacements, collecter les retours, optimiser",
    bp_road_phase4: "Phase 4 : Plein Régime",
    bp_road_phase4_desc: "3 services par jour, contrats d'emplacement fixes, planifier l'expansion",
    bp_road_month: "Mois",

    // Home experience sections
    hero_eyebrow: "Gourmet Mobile · Foodtruck · Depuis 2025",
    hero_stat_budget: "Budget de départ",
    hero_stat_launch: "Mois avant lancement",
    hero_stat_goal: "Objectif journalier",
    hero_scroll: "Défiler",

    concept_pillar_card_title: "Carte compacte",
    concept_pillar_card_text: "Quelques signatures, une attente courte et une décision claire au comptoir.",
    concept_pillar_brand_title: "Marque au quotidien",
    concept_pillar_brand_text: "Truck, uniforme, sac, boîte et wrap parlent le même langage visuel.",
    concept_pillar_route_title: "Logique d'emplacement",
    concept_pillar_route_text: "Lunch spots, parkings d'entreprise et événements planifiés comme une route répétable.",
    concept_note_service_label: "Service",
    concept_note_service_text: "Commande et remise restent sous contrôle",
    concept_note_quality_label: "Qualité",
    concept_note_quality_text: "Recettes et emballages standardisés",
    concept_note_mobility_label: "Mobilité",
    concept_note_mobility_text: "S'adapter aux horaires et à la demande",
    concept_note_brand_label: "Marque",
    concept_note_brand_text: "Cohérente du truck jusqu'au sac",
    concept_media_label: "Emplacement pilote",
    concept_media_number: "Concept",
    concept_media_title: "Un concept mobile avec",
    concept_media_accent: "un niveau restaurant.",

    brand_eyebrow: "Système de marque",
    brand_full_cta: "Voir toute la marque",
    brand_head_pre: "Un",
    brand_head_accent: "système discret",
    brand_head_post: "pour le truck, l'équipe et le take-away.",
    brand_palette_label: "Palette de couleurs",
    brand_palette_note: "Quatre couleurs, de nombreux points de contact",
    brand_palette_ink_name: "Ink",
    brand_palette_ink_desc: "Profondeur & contraste",
    brand_palette_cream_name: "Cream",
    brand_palette_cream_desc: "Espace & calme",
    brand_palette_tan_name: "Tan",
    brand_palette_tan_desc: "Chaleur & texture",
    brand_palette_gold_name: "Gold",
    brand_palette_gold_desc: "Accent & signature",
    brand_rollout_label: "Prêt au déploiement",
    brand_rollout_text: "Digital · Packaging · Uniforme · Emplacement",
    brand_asset_truck_title: "Truck",
    brand_asset_truck_text: "Surfaces sombres, lignes chaudes et logo lisible de loin.",
    brand_asset_packaging_title: "Packaging",
    brand_asset_packaging_text: "Sac, boîte, gobelet et wrap portent la marque jusqu'au client.",
    brand_asset_team_title: "Équipe",
    brand_asset_team_text: "Les uniformes relient clairement service et marque.",
    brand_asset_launch_title: "Lancement",
    brand_asset_launch_text: "Emplacements, route et présence fonctionnent comme un système.",
    brand_mockups_eyebrow: "Mockups en situation",
    brand_mockups_head_pre: "Des points de contact réels avec",
    brand_mockups_head_accent: "du contenu",
    brand_mockups_head_post: ", pas seulement des surfaces logo.",
    brand_mockups_copy: "Les mockups montrent comment packaging, tenue d'équipe et signalétique fonctionnent comme un système: lisibles vite, cohérents avec la marque et proches du moment de vente.",
    brand_mockup_box_title: "Burger Box",
    brand_mockup_box_label: "Signature take-away",
    brand_mockup_box_text: "Logo, motif et sticker rendent l'emballage visible même après l'achat.",
    brand_mockup_wrap_title: "Baguette Wrap",
    brand_mockup_wrap_label: "Comptoir frais",
    brand_mockup_wrap_text: "Le wrap reste sobre et premium pour laisser le produit au premier plan.",
    brand_mockup_counter_title: "Counter Bag",
    brand_mockup_counter_label: "Moment de remise",
    brand_mockup_counter_text: "Le sac devient une petite surface publicitaire entre le truck et le client.",
    brand_mockup_paper_title: "Paper Bag",
    brand_mockup_paper_label: "Route du midi",
    brand_mockup_paper_text: "Lisibilité forte pour bureau, événement, marché et passage spontané.",
    brand_mockup_teamwear_title: "Teamwear",
    brand_mockup_teamwear_label: "Look service",
    brand_mockup_teamwear_text: "Un branding discret sur vêtements foncés rend l'équipe identifiable.",
    brand_mockup_signboard_title: "Signboard",
    brand_mockup_signboard_label: "Signal de rue",
    brand_mockup_signboard_text: "Le panneau rend la marque, la direction et l'offre visibles de loin.",

    menu_head_pre: "Peu de choix,",
    menu_head_accent: "beaucoup de clarté.",
    menu_intro: "Smash burgers, baguettes chaudes et extras sont structurés pour que les clients décident vite et que l'équipe produise proprement.",
    menu_tag_burger: "Smash Burger",
    menu_tag_baguettes: "Baguettes Gourmet",
    menu_tag_extras: "Frites & Boissons",
    menu_value_heat_title: "Chaleur signature",
    menu_value_heat_text: "Les smash patties sont produits vite, chauds et de façon répétable.",
    menu_value_upgrade_title: "Upgrade menu",
    menu_value_upgrade_text: "Boissons, frites et sauces augmentent le ticket sans complexité.",
    menu_value_price_title: "Prix lisibles",
    menu_value_price_text: "Chaque catégorie reste courte, claire et facile à calculer.",

    standards_eyebrow: "Standards",
    standards_head_pre: "Un système opérationnel qui",
    standards_head_accent: "reste calme.",
    standards_copy: "La qualité ne vient pas de plus d'options, mais d'une répétition claire. Chaque standard est une brique de l'exploitation mobile.",
    standards_rule_label: "Règle clé",
    standards_rule_pre: "Moins de variantes.",
    standards_rule_accent: "Plus de contrôle.",
    standard_ingredients_title: "Ingrédients",
    standard_ingredients_text: "Spécifications pour buns, viande, légumes et sauces.",
    standard_recipe_title: "Recette",
    standard_recipe_text: "Quantités, temps de cuisson et montage restent documentés.",
    standard_speed_title: "Tempo",
    standard_speed_text: "Carte courte, stations claires, attente prévisible.",
    standard_packaging_title: "Packaging",
    standard_packaging_text: "Stable au transport et visiblement brandé.",
    standard_control_title: "Contrôle",
    standard_control_text: "Températures, nettoyage et mise en place sous forme de checklist.",
    standard_location_title: "Emplacement",
    standard_location_text: "Électricité, eau, remise et file d'attente sont vérifiées en amont.",

    journey_eyebrow: "Parcours client",
    journey_head_pre: "Du premier regard",
    journey_head_accent: "jusqu'au sac.",
    journey_copy: "L'expérience est courte, mais elle doit fonctionner: voir, comprendre, commander, recevoir. Chaque moment a une mission claire.",
    journey_step_visible_title: "Être visible",
    journey_step_visible_text: "Truck, lumière et marque créent le premier signal à distance.",
    journey_step_order_title: "Commander vite",
    journey_step_order_text: "La carte reste courte pour une décision fluide au comptoir.",
    journey_step_wait_title: "Attendre calmement",
    journey_step_wait_text: "Stations fixes et ingrédients préparés stabilisent le flux.",
    journey_step_takeaway_title: "Emporter la marque",
    journey_step_takeaway_text: "Sac, gobelet et wrap portent l'impression au bureau, à l'événement ou à la maison.",

    workflow_eyebrow: "Workflow",
    workflow_head_pre: "Un petit truck, un",
    workflow_head_accent: "flux précis.",
    workflow_copy: "Le design opérationnel compte autant que le branding. Tout est conçu pour des trajets courts et des rôles clairs.",
    workflow_media_label: "Workflow cuisine",
    workflow_day_label: "Système journalier",
    workflow_phase_prep_title: "Préparation avant ouverture",
    workflow_phase_prep_text: "Mise en place, stations, stock",
    workflow_phase_lunch_title: "Service du midi",
    workflow_phase_lunch_text: "Fréquence maximale, trajets courts",
    workflow_phase_event_title: "Événement / soir",
    workflow_phase_event_text: "Route flexible selon la demande",
    workflow_phase_clean_title: "Nettoyage",
    workflow_phase_clean_text: "Nettoyage, clôture, transmission",
    workflow_lane_buy_title: "Achat",
    workflow_lane_buy_text: "Liste courte, meilleure planification, moins de déchets.",
    workflow_lane_mise_title: "Mise en place",
    workflow_lane_mise_text: "La préparation rend les pics plus calmes.",
    workflow_lane_production_title: "Production",
    workflow_lane_production_text: "Griddle, station baguette et remise comme une ligne.",
    workflow_lane_pace_title: "Tempo",
    workflow_lane_pace_text: "Ticket moyen, attente et débit restent visibles.",
    workflow_lane_roles_title: "Rôles équipe",
    workflow_lane_roles_text: "Caisse, griddle et assemblage sont clairement séparés.",

    business_eyebrow: "Business Plan",
    business_head_pre: "Chiffres, route et marque dans",
    business_head_accent: "un seul modèle.",
    business_copy: "Le plan est pensé comme un système de départ: investissable, mesurable et assez léger pour évoluer après le pilote.",
    business_kpi_invest_label: "Investissement initial",
    business_kpi_invest_text: "Remorque, équipement, branding, autorisation et réserve.",
    business_kpi_margin_label: "Marge cible",
    business_kpi_margin_text: "Calculée autour d'une carte courte et d'une production répétable.",
    business_kpi_pilot_label: "Mois avant pilote",
    business_kpi_pilot_text: "Du setup au soft launch en exploitation pilote.",
    business_invest_title: "Mix d'investissement",
    business_invest_trailer: "Remorque",
    business_invest_equipment: "Équipement",
    business_invest_brand: "Branding",
    business_invest_license: "Licence & réserve",
    business_finance_title: "Logique mensuelle",
    business_finance_revenue: "CA moyen",
    business_finance_cogs: "Coût matières",
    business_finance_staff: "Personnel",
    business_finance_reserve: "Réserve",
    business_product_burger_label: "Smash Burger",
    business_product_burger_value: "4 signatures",
    business_product_baguette_label: "Baguettes Gourmet",
    business_product_baguette_value: "4 variantes",
    business_product_extras_label: "Extras",
    business_product_extras_value: "Frites, sauces, boissons",
    business_roadmap_label: "Roadmap",
    business_road_setup_title: "Setup",
    business_road_setup_text: "Truck, équipement, branding",
    business_road_test_title: "Test",
    business_road_test_text: "Recettes, achats, horaires de service",
    business_road_pilot_title: "Pilote",
    business_road_pilot_text: "Lunch spots et créneaux événementiels",
    business_road_scale_title: "Scale",
    business_road_scale_text: "Playbook pour plus d'emplacements",
    business_closing_head_pre: "La marque aide à vendre, mais le",
    business_closing_head_accent: "flux décide.",
    business_closing_copy: "C'est pourquoi le plan relie assets de marque, choix d'emplacement, menu engineering et indicateurs dans un modèle de départ maîtrisable.",
    business_launch_cta: "Voir le lancement",

    launch_eyebrow: "Plan de lancement",
    launch_head_pre: "Du premier créneau à",
    launch_head_accent: "l'exploitation répétable.",
    launch_copy: "Burger & Baguette ne démarre pas comme un grand show, mais comme un pilote mesurable: bons emplacements, opérations propres, marque claire.",
    launch_business_cta: "Voir le business plan",
    launch_menu_cta: "Menu",
    launch_check_locations_title: "Emplacements pilotes",
    launch_check_locations_text: "Tester d'abord quelques lieux avec une fréquence claire.",
    launch_check_route_title: "Route",
    launch_check_route_text: "Planifier midi, after-work et événements comme une semaine répétable.",
    launch_check_metrics_title: "Indicateurs",
    launch_check_metrics_text: "Suivre ticket moyen, attente, chiffre quotidien et taux de retour.",
    launch_check_scale_title: "Mise à l'échelle",
    launch_check_scale_text: "Après le pilote, fixer recettes et rôles d'équipe dans un playbook.",

    footer_tagline: "La Qualité en Mouvement",
    footer_copy: "Burgers artisanaux, baguettes fraîches et présence claire pour une gastronomie mobile premium.",
    footer_highlight_mobile: "Gourmet Mobile",
    footer_highlight_truck: "Foodtruck",
    footer_highlight_event: "Événement & Midi",
    footer_nav_title: "Explorer",
    footer_meta: "Gourmet Mobile · Foodtruck",

    footer_rights: "Tous droits réservés",
    footer_concept: "Un concept de Burger & Baguette",
  },
  ar: {
    nav_home: "الرئيسية",
    nav_concept: "المفهوم",
    nav_brand: "الهوية",
    nav_menu: "القائمة",
    nav_journey: "الرحلة",
    nav_workflow: "التشغيل",
    nav_businessplan: "خطة العمل",
    nav_contact: "اتصل بنا",

    hero_tagline: "الجودة تلتقي بالتنقل",
    hero_subtitle: "برغر سماش فاخر وباجيت جورميه – طازج، في أي مكان تريده.",
    hero_cta: "استكشف القائمة",
    hero_bp_cta: "عرض خطة العمل",

    concept_title: "المفهوم",
    concept_subtitle: "منتجات فاخرة. أسعار عادلة. مواقع مرنة.",
    concept_text: "يجمع Burger & Baguette بين شغف البرغر المصنوع يدوياً وأناقة الباجيت الفرنسي. تقدم شاحنة الطعام لدينا أفضل أطعمة الشوارع مباشرة إلى المواقع المزدحمة – مراكز التسوق والفعاليات ومواقف سيارات الشركات.",
    concept_quality: "جودة فاخرة",
    concept_quality_desc: "مكونات طازجة فقط، تُسلَّم يومياً",
    concept_mobile: "أقصى مرونة",
    concept_mobile_desc: "في أي مكان يوجد فيه العملاء",
    concept_fair: "أسعار عادلة",
    concept_fair_desc: "تجربة ذواقة للجميع",

    menu_title: "القائمة",
    menu_burgers: "برغر سماش",
    menu_baguettes: "باجيت جورميه",
    menu_double: "كباتي مزدوج",
    menu_double_desc: "+3.00 € إضافة",
    menu_deal: "وجبة كاملة",
    menu_deal_desc: "أي برغر أو باجيت كوجبة: +5.00 € = بطاطس + مشروب + صوص",
    menu_fresh: "طازج دائماً",
    menu_fresh_desc: "جميع المنتجات تُحضَّر طازجة في الموقع",

    burger_classic: "كلاسيك سماش",
    burger_classic_desc: "باتي لحم بقري، بصل، صوص البيت",
    burger_cheese: "تشيزبرغر",
    burger_cheese_desc: "باتي لحم بقري، شيدر، بصل",
    burger_bacon: "بيكون تشيز",
    burger_bacon_desc: "باتي لحم بقري، شيدر، بيكون مقرمش، بصل",
    burger_onion: "بصل مكرمل",
    burger_onion_desc: "باتي لحم بقري، شيدر، بصل مكرمل، جرجير",

    bag_hack: "لحم وجبن",
    bag_hack_desc: "لحم مفروم متبل، شيدر مذاب، بصل",
    bag_merguez: "باجيت ستيك",
    bag_merguez_desc: "ستيك لحم بقري طري، بصل مقلي، صوص فلفل",
    bag_philly: "باجيت فيلي تشيز",
    bag_philly_desc: "شرائح لحم بقري طرية، فلفل، بصل، جبن بروفولوني مذاب",
    bag_veggi: "خضار متوسطي",
    bag_veggi_desc: "خضار مشوية، جبن فيتا، زيتون، جرجير، خل بلسمي",

    menu_extras: "المرفقات والمشروبات",
    menu_fries: "بطاطس مقلية",
    menu_fries_desc: "مقلية طازجة، مملحة حسب الذوق",
    menu_sauce: "الصوصات",
    menu_sauce_desc: "كاتشب، مايو، BBQ، تشيلي، ثوم",
    menu_drinks: "مشروبات غازية",
    menu_cola: "كولا",
    menu_fanta: "فانتا",
    menu_sprite: "سبرايت",
    menu_icetea_lemon: "شاي مثلج ليمون",
    menu_icetea_peach: "شاي مثلج خوخ",
    menu_water: "ماء طبيعي",

    bp_title: "خطة العمل",
    bp_tab_overview: "نظرة عامة",
    bp_tab_products: "المنتجات",
    bp_tab_finance: "الماليات",
    bp_tab_locations: "المواقع",
    bp_tab_roadmap: "خارطة الطريق",

    bp_overview_title: "المفهوم والرؤية",
    bp_overview_text: "Burger & Baguette هو مفهوم شاحنة طعام متنقلة تقدم برغر سماش فاخر وباجيت جورميه في المواقع ذات الحركة العالية. يجمع المفهوم بين الجودة وسهولة الوصول.",
    bp_invest_title: "الاستثمار",
    bp_invest_total: "إجمالي الاستثمار",
    bp_invest_trailer: "مقطورة البيع VK 523",
    bp_invest_equip: "معدات المطبخ",
    bp_invest_brand: "العلامة التجارية والتغليف",
    bp_invest_license: "التراخيص والتصاريح",
    bp_invest_reserve: "احتياطي رأس المال العامل",

    bp_finance_title: "الربحية",
    bp_revenue_min: "الإيرادات (الحد الأدنى)",
    bp_revenue_max: "الإيرادات (الحد الأقصى)",
    bp_revenue_avg: "الإيرادات (المتوسط)",
    bp_cogs: "تكلفة البضائع",
    bp_rent: "الإيجار والمرافق",
    bp_staff: "تكاليف الموظفين",
    bp_other: "تكاليف أخرى",
    bp_profit: "الربح قبل الضرائب",
    bp_monthly: "/ شهر",
    bp_breakeven: "نقطة التعادل",
    bp_breakeven_val: "حوالي 25,300 €",
    bp_roi: "فترة الاسترداد",
    bp_roi_val: "حوالي 2–3 أشهر",
    bp_margin: "هامش الربح",
    bp_margin_val: "38.5%",

    bp_loc_title: "استراتيجية المواقع",
    bp_loc_morning: "التحضير",
    bp_loc_morning_desc: "التجهيز والإعداد (9:00–11:00 ص) – لا مبيعات",
    bp_loc_midday: "وردية الغداء",
    bp_loc_midday_desc: "الافتتاح وخدمة الغداء (11:00 ص–3:00 م)",
    bp_loc_evening: "وردية المساء",
    bp_loc_evening_desc: "الفعاليات، الأسواق، المهرجانات (3:00–9:00 م)",
    bp_loc_types: "أنواع المواقع",
    bp_loc_mall: "مراكز التسوق",
    bp_loc_event: "الفعاليات",
    bp_loc_corp: "مواقف الشركات",
    bp_loc_market: "الأسواق الأسبوعية",

    bp_road_title: "خطة التنفيذ",
    bp_road_phase1: "المرحلة 1: التحضير",
    bp_road_phase1_desc: "طلب المقطورة، تقديم طلبات التصاريح، إنهاء العلامة التجارية",
    bp_road_phase2: "المرحلة 2: الإعداد",
    bp_road_phase2_desc: "تركيب المطبخ، تأمين الموردين، توظيف الموظفين",
    bp_road_phase3: "المرحلة 3: الإطلاق التجريبي",
    bp_road_phase3_desc: "اختبار المواقع الأولى، جمع الملاحظات، تحسين العمليات",
    bp_road_phase4: "المرحلة 4: التشغيل الكامل",
    bp_road_phase4_desc: "3 وردات يومياً، عقود مواقع ثابتة، التخطيط للتوسع",
    bp_road_month: "شهر",

    // Home experience sections
    hero_eyebrow: "جورميه متنقل · شاحنة طعام · منذ 2025",
    hero_stat_budget: "ميزانية البداية",
    hero_stat_launch: "أشهر حتى الإطلاق",
    hero_stat_goal: "هدف يومي",
    hero_scroll: "تمرير",

    concept_pillar_card_title: "قائمة مختصرة",
    concept_pillar_card_text: "أصناف مميزة قليلة، انتظار قصير، وقرار واضح عند الكاونتر.",
    concept_pillar_brand_title: "هوية في كل تفصيلة",
    concept_pillar_brand_text: "الشاحنة والزي والكيس والعلبة والغلاف تتحدث بنفس اللغة البصرية.",
    concept_pillar_route_title: "منطق المواقع",
    concept_pillar_route_text: "مواقع الغداء، مواقف الشركات والفعاليات تتحول إلى مسار قابل للتكرار.",
    concept_note_service_label: "الخدمة",
    concept_note_service_text: "من الطلب إلى التسليم تحت السيطرة",
    concept_note_quality_label: "الجودة",
    concept_note_quality_text: "وصفات وتغليف بمعايير موحدة",
    concept_note_mobility_label: "التنقل",
    concept_note_mobility_text: "تلبية الطلب حسب الوقت والموقع بمرونة",
    concept_note_brand_label: "الهوية",
    concept_note_brand_text: "تجربة متناسقة من الشاحنة حتى كيس الطلب",
    concept_media_label: "موقع تجريبي",
    concept_media_number: "المفهوم",
    concept_media_title: "مفهوم متنقل بمستوى",
    concept_media_accent: "مطعم راق.",

    brand_eyebrow: "نظام الهوية",
    brand_full_cta: "عرض الهوية كاملة",
    brand_head_pre: "نظام",
    brand_head_accent: "هادئ ومتماسك",
    brand_head_post: "للشاحنة والفريق والتغليف.",
    brand_palette_label: "لوحة الألوان",
    brand_palette_note: "أربعة ألوان، ونقاط تواصل كثيرة",
    brand_palette_ink_name: "Ink",
    brand_palette_ink_desc: "عمق وتباين",
    brand_palette_cream_name: "Cream",
    brand_palette_cream_desc: "مساحة وهدوء",
    brand_palette_tan_name: "Tan",
    brand_palette_tan_desc: "دفء وملمس",
    brand_palette_gold_name: "Gold",
    brand_palette_gold_desc: "لمسة وهوية",
    brand_rollout_label: "جاهز للتطبيق",
    brand_rollout_text: "رقمي · تغليف · زي الفريق · الموقع",
    brand_asset_truck_title: "الشاحنة",
    brand_asset_truck_text: "أسطح داكنة، خطوط دافئة، وشعار واضح من مسافة.",
    brand_asset_packaging_title: "التغليف",
    brand_asset_packaging_text: "الكيس والعلبة والكوب والغلاف يحملون الهوية حتى يد العميل.",
    brand_asset_team_title: "الفريق",
    brand_asset_team_text: "الزي الموحد يجعل الخدمة والهوية يظهران كمنظومة واحدة.",
    brand_asset_launch_title: "الإطلاق",
    brand_asset_launch_text: "المواقع والمسار والحضور البصري يعملون كنظام واحد.",
    brand_mockups_eyebrow: "نماذج مستخدمة",
    brand_mockups_head_pre: "نقاط تلامس حقيقية مع",
    brand_mockups_head_accent: "محتوى",
    brand_mockups_head_post: "، لا مجرد مساحات للشعار.",
    brand_mockups_copy: "توضح النماذج كيف يعمل التغليف، وملابس الفريق، واللافتات كنظام واحد: سريع القراءة، مناسب للهوية، وقريب من لحظة البيع.",
    brand_mockup_box_title: "علبة البرغر",
    brand_mockup_box_label: "توقيع التيك أواي",
    brand_mockup_box_text: "الشعار والنمط والملصق يجعلون التغليف مرئيا حتى بعد الشراء.",
    brand_mockup_wrap_title: "غلاف الباجيت",
    brand_mockup_wrap_label: "كاونتر طازج",
    brand_mockup_wrap_text: "يبقى الغلاف هادئا وفاخرا حتى يظل المنتج في المقدمة.",
    brand_mockup_counter_title: "كيس التسليم",
    brand_mockup_counter_label: "لحظة التسليم",
    brand_mockup_counter_text: "يتحول الكيس إلى مساحة إعلان صغيرة بين الشاحنة والعميل.",
    brand_mockup_paper_title: "كيس ورقي",
    brand_mockup_paper_label: "مسار الغداء",
    brand_mockup_paper_text: "وضوح قوي للمكتب والفعالية والسوق والزبائن المارين.",
    brand_mockup_teamwear_title: "زي الفريق",
    brand_mockup_teamwear_label: "مظهر الخدمة",
    brand_mockup_teamwear_text: "هوية هادئة على ملابس داكنة تجعل الفريق واضحا وسهل التمييز.",
    brand_mockup_signboard_title: "لافتة الشارع",
    brand_mockup_signboard_label: "إشارة من بعيد",
    brand_mockup_signboard_text: "تجعل اللافتة الهوية والاتجاه والعرض مفهومين من مسافة.",

    menu_head_pre: "خيارات أقل،",
    menu_head_accent: "وضوح أكثر.",
    menu_intro: "برغر سماش، باجيت دافئ، وإضافات مرتبة بحيث يقرر العميل بسرعة وينتج الفريق بسلاسة.",
    menu_tag_burger: "برغر سماش",
    menu_tag_baguettes: "باجيت جورميه",
    menu_tag_extras: "بطاطس ومشروبات",
    menu_value_heat_title: "حرارة مميزة",
    menu_value_heat_text: "تنتج باتيز السماش بسرعة وحرارة عالية وبنفس النتيجة كل مرة.",
    menu_value_upgrade_title: "ترقية الوجبة",
    menu_value_upgrade_text: "المشروبات والبطاطس والصوصات ترفع قيمة الطلب دون تعقيد التشغيل.",
    menu_value_price_title: "أسعار واضحة",
    menu_value_price_text: "كل فئة تبقى قصيرة، مفهومة، وسهلة الحساب.",

    standards_eyebrow: "المعايير",
    standards_head_pre: "نظام تشغيل",
    standards_head_accent: "يبقى هادئا.",
    standards_copy: "الجودة لا تأتي من كثرة الخيارات، بل من تكرار واضح. كل معيار هو جزء أساسي من تشغيل الشاحنة.",
    standards_rule_label: "القاعدة الأساسية",
    standards_rule_pre: "تنويعات أقل.",
    standards_rule_accent: "تحكم أكثر.",
    standard_ingredients_title: "المكونات",
    standard_ingredients_text: "مواصفات واضحة للخبز واللحم والخضار والصوصات.",
    standard_recipe_title: "الوصفة",
    standard_recipe_text: "الكميات، أوقات الطهي، وطريقة التجميع تبقى موثقة.",
    standard_speed_title: "السرعة",
    standard_speed_text: "قائمة قصيرة، محطات واضحة، ووقت انتظار قابل للتوقع.",
    standard_packaging_title: "التغليف",
    standard_packaging_text: "ثابت أثناء النقل ويحمل الهوية بوضوح.",
    standard_control_title: "الرقابة",
    standard_control_text: "الحرارة، التنظيف، والتجهيز اليومي ضمن قائمة فحص.",
    standard_location_title: "الموقع",
    standard_location_text: "الكهرباء، الماء، التسليم وطابور الانتظار يتم فحصها مسبقا.",

    journey_eyebrow: "رحلة العميل",
    journey_head_pre: "من أول نظرة إلى",
    journey_head_accent: "لحظة استلام الطلب.",
    journey_copy: "التجربة قصيرة، لكنها يجب أن تكون واضحة: يرى العميل، يفهم، يطلب، ثم يستلم. لكل لحظة وظيفة محددة.",
    journey_step_visible_title: "الظهور من بعيد",
    journey_step_visible_text: "الشاحنة والإضاءة والهوية تصنع أول انطباع قبل الوصول.",
    journey_step_order_title: "طلب سريع",
    journey_step_order_text: "تبقى القائمة مختصرة حتى يتم القرار عند الكاونتر دون احتكاك.",
    journey_step_wait_title: "انتظار هادئ",
    journey_step_wait_text: "محطات ثابتة ومكونات جاهزة تحافظ على استقرار الحركة.",
    journey_step_takeaway_title: "حمل الهوية",
    journey_step_takeaway_text: "الكيس والكوب والغلاف ينقلون الانطباع إلى المكتب أو الفعالية أو البيت.",

    workflow_eyebrow: "سير التشغيل",
    workflow_head_pre: "شاحنة صغيرة،",
    workflow_head_accent: "تشغيل دقيق.",
    workflow_copy: "تصميم التشغيل مهم مثل الهوية البصرية. كل شيء مبني على مسارات قصيرة وأدوار واضحة.",
    workflow_media_label: "سير عمل المطبخ",
    workflow_day_label: "النظام اليومي",
    workflow_phase_prep_title: "تحضير قبل الافتتاح",
    workflow_phase_prep_text: "تجهيز المكونات، المحطات، والمخزون",
    workflow_phase_lunch_title: "خدمة الغداء",
    workflow_phase_lunch_text: "أعلى حركة، وأقصر مسارات",
    workflow_phase_event_title: "فعالية / مساء",
    workflow_phase_event_text: "مسار مرن حسب الطلب",
    workflow_phase_clean_title: "إغلاق وتنظيف",
    workflow_phase_clean_text: "تنظيف، إقفال، وتسليم",
    workflow_lane_buy_title: "الشراء",
    workflow_lane_buy_text: "قائمة توريد قصيرة، تخطيط أفضل، وهدر أقل.",
    workflow_lane_mise_title: "التجهيز المسبق",
    workflow_lane_mise_text: "التحضير يجعل أوقات الذروة أكثر هدوءا.",
    workflow_lane_production_title: "الإنتاج",
    workflow_lane_production_text: "الشواية، محطة الباجيت، والتسليم كخط واحد.",
    workflow_lane_pace_title: "الإيقاع",
    workflow_lane_pace_text: "قيمة الطلب، وقت الانتظار، وسرعة الخدمة تبقى واضحة.",
    workflow_lane_roles_title: "أدوار الفريق",
    workflow_lane_roles_text: "الكاشير، الشواية، والتجميع مفصولة بوضوح.",

    business_eyebrow: "خطة العمل",
    business_head_pre: "الأرقام والمسار والهوية في",
    business_head_accent: "نموذج واحد.",
    business_copy: "الخطة مصممة كنظام بداية: قابلة للاستثمار، قابلة للقياس، وخفيفة بما يكفي للتعديل بعد التشغيل التجريبي.",
    business_kpi_invest_label: "استثمار البداية",
    business_kpi_invest_text: "المقطورة، المعدات، الهوية، التصاريح والاحتياطي.",
    business_kpi_margin_label: "الهامش المستهدف",
    business_kpi_margin_text: "محسوب على قائمة قصيرة وإنتاج قابل للتكرار.",
    business_kpi_pilot_label: "أشهر حتى التجربة",
    business_kpi_pilot_text: "من التجهيز إلى الإطلاق التجريبي في التشغيل الأول.",
    business_invest_title: "مزيج الاستثمار",
    business_invest_trailer: "المقطورة",
    business_invest_equipment: "المعدات",
    business_invest_brand: "الهوية",
    business_invest_license: "التراخيص والاحتياطي",
    business_finance_title: "منطق الشهر",
    business_finance_revenue: "متوسط الإيراد",
    business_finance_cogs: "تكلفة المواد",
    business_finance_staff: "الفريق",
    business_finance_reserve: "الاحتياطي",
    business_product_burger_label: "برغر سماش",
    business_product_burger_value: "4 أصناف مميزة",
    business_product_baguette_label: "باجيت جورميه",
    business_product_baguette_value: "4 تنويعات",
    business_product_extras_label: "إضافات",
    business_product_extras_value: "بطاطس، صوصات، مشروبات",
    business_roadmap_label: "خارطة الطريق",
    business_road_setup_title: "التجهيز",
    business_road_setup_text: "الشاحنة، المعدات، الهوية",
    business_road_test_title: "الاختبار",
    business_road_test_text: "الوصفات، الشراء، أوقات الخدمة",
    business_road_pilot_title: "التجربة",
    business_road_pilot_text: "مواقع الغداء وفتحات الفعاليات",
    business_road_scale_title: "التوسع",
    business_road_scale_text: "دليل تشغيل لمواقع إضافية",
    business_closing_head_pre: "الهوية تساعد على البيع، لكن",
    business_closing_head_accent: "التشغيل هو الحاسم.",
    business_closing_copy: "لذلك تربط الخطة عناصر الهوية، اختيار الموقع، هندسة القائمة، ونقاط القياس في نموذج بداية واضح.",
    business_launch_cta: "عرض الإطلاق",

    launch_eyebrow: "خطة الإطلاق",
    launch_head_pre: "من أول موقع إلى",
    launch_head_accent: "تشغيل قابل للتكرار.",
    launch_copy: "لا يبدأ Burger & Baguette كعرض كبير، بل كتجربة قابلة للقياس: مواقع جيدة، تشغيل نظيف، وهوية واضحة.",
    launch_business_cta: "عرض خطة العمل",
    launch_menu_cta: "القائمة",
    launch_check_locations_title: "مواقع تجريبية",
    launch_check_locations_text: "اختبار مواقع قليلة أولا بحركة واضحة.",
    launch_check_route_title: "المسار",
    launch_check_route_text: "تخطيط الغداء، نهاية الدوام والفعاليات كأسبوع متكرر.",
    launch_check_metrics_title: "المؤشرات",
    launch_check_metrics_text: "متابعة قيمة الطلب، وقت الانتظار، الإيراد اليومي ونسبة العودة.",
    launch_check_scale_title: "التوسع",
    launch_check_scale_text: "بعد التجربة، تثبيت الوصفات وأدوار الفريق كدليل تشغيل.",

    footer_tagline: "الجودة تلتقي بالتنقل",
    footer_copy: "برغر حرفي، باجيت طازج، وحضور واضح لتجربة طعام متنقلة بطابع فاخر.",
    footer_highlight_mobile: "جورميه متنقل",
    footer_highlight_truck: "شاحنة طعام",
    footer_highlight_event: "فعاليات وغداء",
    footer_nav_title: "استكشف",
    footer_meta: "جورميه متنقل · شاحنة طعام",

    footer_rights: "جميع الحقوق محفوظة",
    footer_concept: "مفهوم من Burger & Baguette",
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguage] = useState<Language>("de");

  const t = (key: string): string => {
    return translations[language][key] || translations["de"][key] || key;
  };

  const dir: "ltr" | "rtl" = language === "ar" ? "rtl" : "ltr";

  useEffect(() => {
    document.documentElement.lang = language;
    document.documentElement.dir = dir;
  }, [dir, language]);

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, dir }}>
      <div dir={dir} lang={language}>
        {children}
      </div>
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error("useLanguage must be used within LanguageProvider");
  return ctx;
}
